version: '2'
services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgres/data
      POSTGRES_DB: sample
    volumes:
      - pg-data:/var/lib/postgres/data
    ports:
      - 5433:5432/tcp #expose to another port if you have problem to conne
  flask-app:
    image: project5
    environment:
      MB_DB_DBNAME: sample
      MB_DB_HOST: postgres-db
      MB_DB_PASS: postgres
      MB_DB_PORT: 5432
      MB_DB_TYPE : postgres
      MB_DB_USER: admin
    volumes: 
      - ./app:/app
    links:
      - postgres-db:postgres-db
    ports:
      -  5000:5000/tcp
volumes:
  pg-data:
    external: true